### ISSUE TITLE
I want to love it. But Virustotal hates it.

### ISSUE THREAD

**Issue by IamUSER** [iammrbt/cfUpdaterPy#1]
https://www.virustotal.com/gui/file/c70c43ee2b3b18acd3bb916bb4853067115d5fda686cdbe837f59769ce31fa6a

It did drop by 10 hits since I last scanned. Just soyaknow.

**Comment by iammrbt** [comment]
Probably because it's just a python wrapped executable. The source code is there and available if you want to just run it with python or you could use it in windows sandbox to ensure it's safe.
