### ISSUE TITLE
installing the Tkinter module linux distros - not mentioned in setup

### ISSUE THREAD

**Issue by airxzen** [iammrbt/cfUpdaterPy#3]
Hi! I thought it'd be important to mention that in my instance I had to run 

"sudo apt install python3-tk" 

For anyone who has a single idea of what they're doing this is a no-brainer but for plebs like myself, it took me a little bit to figure out what the error meant. 

Should this be included in the setup as Tkinter is required for this to run (or at least that's how I got it to run)

Thank you for this btw! This is the only thing that has worked for me. I have been trying for HOURS

**Comment by iammrbt** [comment]
Thanks @airxzen ! I have updated the readme with that clarification to help future users! I'll spend some more time on this this week to make some other minor things I've been wishing existed.
